export const TRIVIA_QUESTIONS_GET_REQUESTED = 'TRIVIA_QUESTIONS_GET_REQUESTED';
export const TRIVIA_QUESTIONS_GET_ERROR = 'TRIVIA_QUESTIONS_GET_ERROR';
export const TRIVIA_QUESTIONS_GET_SUCCESSFUL = 'TRIVIA_QUESTIONS_GET_SUCCESSFUL';
export const TRIVIA_SET_ANSWER = 'TRIVIA_SET_ANSWER';
export const TRIVIA_RESTART = 'TRIVIA_RESTART';
